apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 727646470302.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newName: 727646470302.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newTag: cab2a962
- name: 940168446867.dkr.ecr.ap-northeast-1.amazonaws.com/hhs-demo-frontend
  newName: 940168446867.dkr.ecr.ap-northeast-1.amazonaws.com/hhs-demo-frontend
  newTag: a3367dd3
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
